version: '3'


services:
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        ports:
          - '80:80'
          - '443:443'
        volumes:
          - ./nginx/default.conf:/tmp/default.template
          - ./test:/var/www/html:rw,cached
          - ./certs:/etc/certs
        restart: always
        entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'